theme: jekyll-theme-minimal
title: Daniel Díaz Quílez
logo: /assets/images/me.jpg
description: >
  Master's student in mathematics<br>
  Email: <a href="mailto:daniel.diaz@helsinki.fi">daniel.diaz@helsinki.fi</a><br>
  Github: <a href="https://github.com/tempate">tempate</a>
show_downloads: false
google_analytics:

header_pages:
  - publications.md
  - software.md
